const USER='avtsye',API='https://api.github.com',TTL=15*60*1000;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ago=d=>{let n=(Date.now()-new Date(d))/1000;if(n<3600)return 'לפני '+Math.max(1,Math.floor(n/60))+' דקות';if(n<86400)return 'לפני '+Math.floor(n/3600)+' שעות';if(n<604800)return 'לפני '+Math.floor(n/86400)+' ימים';return new Intl.DateTimeFormat('he-IL',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d))};
let all=[];
function cacheGet(k){try{let x=JSON.parse(localStorage.getItem(k));return x&&Date.now()-x.t<TTL?x.v:null}catch{return null}}function cacheSet(k,v){try{localStorage.setItem(k,JSON.stringify({t:Date.now(),v}))}catch{}}
async function get(path){let k='gh:'+path,c=cacheGet(k);if(c)return c;let r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw Error(r.status);let v=await r.json();cacheSet(k,v);return v}
function theme(){let saved=localStorage.getItem('theme'),dark=saved?saved==='dark':matchMedia('(prefers-color-scheme:dark)').matches;document.documentElement.dataset.theme=dark?'dark':'light';$('#theme').textContent=dark?'☀':'☾'}theme();$('#theme').onclick=()=>{let d=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=d?'dark':'light';localStorage.setItem('theme',d?'dark':'light');theme()}
function render(){let q=$('#q').value.toLowerCase(),lang=$('#lang').value,sort=$('#sort').value;let rows=all.filter(r=>!r.archived&&!r.topics.includes('hide-homepage')).filter(r=>(r.name+' '+(r.description||'')+' '+r.topics.join(' ')).toLowerCase().includes(q)).filter(r=>!lang||r.language===lang);rows.sort((a,b)=>sort==='stars'?b.stargazers_count-a.stargazers_count:sort==='name'?a.name.localeCompare(b.name):new Date(b.pushed_at)-new Date(a.pushed_at));$('#repos').innerHTML=rows.map(r=>{let feat=r.topics.includes('featured'),site=r.homepage&&/^https?:/.test(r.homepage)?r.homepage:null;return `<article class="card ${feat?'featured':''}"><div class="icon">${feat?'★':'⌘'}</div><h3>${esc(r.name)}</h3><p>${esc(r.description||'מאגר ציבורי ב‑GitHub')}</p><div class="meta">${r.language?`<span class="pill">${esc(r.language)}</span>`:''}<span class="pill">★ ${r.stargazers_count}</span><span class="pill">⑂ ${r.forks_count}</span><span class="pill">${r.open_issues_count} issues</span></div><div class="topics">${r.topics.filter(t=>t!=='featured').slice(0,5).map(t=>`<span class="pill topic">#${esc(t)}</span>`).join('')}</div><div class="actions"><a class="smallbtn" href="${r.html_url}" target="_blank" rel="noopener">GitHub ↗</a>${site?`<a class="smallbtn" href="${esc(site)}" target="_blank" rel="noopener">אתר חי ↗</a>`:''}<button class="smallbtn" onclick="details('${esc(r.name)}',this)">פרטים חיים</button></div><div class="updated">עודכן ${ago(r.pushed_at)}</div></article>`}).join('')||'<div class="empty">לא נמצאו מאגרים שמתאימים לסינון.</div>'}
async function details(name,btn){btn.disabled=true;btn.textContent='טוען…';try{let [rel,langs]=await Promise.all([get('/repos/'+USER+'/'+name+'/releases/latest').catch(()=>null),get('/repos/'+USER+'/'+name+'/languages').catch(()=>({}))]);let txt=Object.keys(langs).slice(0,4).join(', ')||'לא זוהו';btn.outerHTML=`<span class="pill">שפות: ${esc(txt)}</span>${rel?`<a class="smallbtn" href="${rel.html_url}" target="_blank">Release: ${esc(rel.tag_name)}</a>`:''}`}catch{btn.textContent='לא זמין';btn.disabled=false}}
async function load(){try{let [u,repos,events]=await Promise.all([get('/users/'+USER),get('/users/'+USER+'/repos?per_page=100&sort=updated&type=owner'),get('/users/'+USER+'/events/public?per_page=12').catch(()=>[])]);all=repos;document.title=(u.name||u.login)+' — GitHub Home';['avatar','navAvatar'].forEach(id=>$('#'+id).src=u.avatar_url);$('#name').textContent=u.name||u.login;$('#navName').textContent=u.name||u.login;$('#login').textContent='@'+u.login;$('#bio').textContent=u.bio||'פרויקטים, כלים וניסויים שאני בונה. הנתונים בדף נטענים ישירות מ‑GitHub ומתעדכנים אוטומטית.';$('#repoCount').textContent=u.public_repos;$('#followers').textContent=u.followers;$('#following').textContent=u.following;['gh','footerGh'].forEach(id=>$('#'+id).href=u.html_url);$('#contact').href=u.email?'mailto:'+u.email:u.html_url;let langs=[...new Set(repos.map(r=>r.language).filter(Boolean))].sort();$('#lang').innerHTML='<option value="">כל השפות</option>'+langs.map(x=>`<option>${esc(x)}</option>`).join('');render();$('#activity').innerHTML=events.slice(0,8).map(e=>`<div class="event"><b>${esc(e.repo.name.replace(USER+'/',''))}</b><span>${esc(e.type.replace('Event',''))} · ${ago(e.created_at)}</span></div>`).join('')||'<div class="empty">אין פעילות ציבורית אחרונה להצגה.</div>';$('#updated').textContent='רענון נתונים: '+new Intl.DateTimeFormat('he-IL',{hour:'2-digit',minute:'2-digit'}).format(new Date())}catch(e){let stale=[];try{Object.keys(localStorage).filter(k=>k.startsWith('gh:')).forEach(k=>{});}catch{}$('#repos').innerHTML='<div class="empty">GitHub אינו זמין כרגע. נסה לרענן בעוד מעט.</div>'}}
['q','lang','sort'].forEach(id=>$('#'+id).addEventListener(id==='q'?'input':'change',render));load();